theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/mribeiro/Timetracker/releases/latest/download/Timetracker.tar.gz
  another_url: https://github.com/mribeiro/Timetracker/releases/latest
